name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Validate keymaps
        run: python3 scripts/validate_keymaps.py

      - name: Test, verify and build
        run: |
          ./gradlew \
            test \
            verifyPluginProjectConfiguration \
            verifyPluginStructure \
            buildPlugin

      - name: Upload plugin
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}
          path: build/distributions/*.zip
          if-no-files-found: error
          retention-days: 7
